dist: trusty
sudo: required

language: cpp
compiler: gcc

env:
  global:
    - NUM_THREADS=4
  matrix:
    - BUILD_NAME="default-cmake"
    
cache:
  apt: true

before_script:
  - sudo -E ./scripts/travis/install-deps.sh

script:
  - mkdir -p build && cd build && cmake .. -DCPU_ONLY_TEST
  - make all
  - ./test_synced_memory
  - ./test_tensor
